// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: node.proto

package avsproto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageOp int32

const (
	MessageOp_Unset              MessageOp = 0
	MessageOp_MonitorTaskTrigger MessageOp = 1
	MessageOp_CancelTask         MessageOp = 2
	MessageOp_DeleteTask         MessageOp = 3
	MessageOp_CompletedTask      MessageOp = 4
)

// Enum value maps for MessageOp.
var (
	MessageOp_name = map[int32]string{
		0: "Unset",
		1: "MonitorTaskTrigger",
		2: "CancelTask",
		3: "DeleteTask",
		4: "CompletedTask",
	}
	MessageOp_value = map[string]int32{
		"Unset":              0,
		"MonitorTaskTrigger": 1,
		"CancelTask":         2,
		"DeleteTask":         3,
		"CompletedTask":      4,
	}
)

func (x MessageOp) Enum() *MessageOp {
	p := new(MessageOp)
	*p = x
	return p
}

func (x MessageOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageOp) Descriptor() protoreflect.EnumDescriptor {
	return file_node_proto_enumTypes[0].Descriptor()
}

func (MessageOp) Type() protoreflect.EnumType {
	return &file_node_proto_enumTypes[0]
}

func (x MessageOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageOp.Descriptor instead.
func (MessageOp) EnumDescriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

type Checkin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Status        *Checkin_Status        `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	MetricsPort   int32                  `protobuf:"varint,6,opt,name=metricsPort,proto3" json:"metricsPort,omitempty"`
	RemoteIP      string                 `protobuf:"bytes,7,opt,name=remoteIP,proto3" json:"remoteIP,omitempty"`
	BlockNumber   int64                  `protobuf:"varint,8,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	EventCount    int64                  `protobuf:"varint,9,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkin) Reset() {
	*x = Checkin{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkin) ProtoMessage() {}

func (x *Checkin) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkin.ProtoReflect.Descriptor instead.
func (*Checkin) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *Checkin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Checkin) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Checkin) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Checkin) GetStatus() *Checkin_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Checkin) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Checkin) GetMetricsPort() int32 {
	if x != nil {
		return x.MetricsPort
	}
	return 0
}

func (x *Checkin) GetRemoteIP() string {
	if x != nil {
		return x.RemoteIP
	}
	return ""
}

func (x *Checkin) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Checkin) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

type CheckinResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckinResp) Reset() {
	*x = CheckinResp{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckinResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinResp) ProtoMessage() {}

func (x *CheckinResp) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinResp.ProtoReflect.Descriptor instead.
func (*CheckinResp) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *CheckinResp) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SyncMessagesReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Signature      []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	MonotonicClock int64                  `protobuf:"varint,4,opt,name=monotonic_clock,json=monotonicClock,proto3" json:"monotonic_clock,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncMessagesReq) Reset() {
	*x = SyncMessagesReq{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessagesReq) ProtoMessage() {}

func (x *SyncMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessagesReq.ProtoReflect.Descriptor instead.
func (*SyncMessagesReq) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *SyncMessagesReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncMessagesReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SyncMessagesReq) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SyncMessagesReq) GetMonotonicClock() int64 {
	if x != nil {
		return x.MonotonicClock
	}
	return 0
}

type SyncMessagesResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message id is used to support dedup
	Id            string                         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Op            MessageOp                      `protobuf:"varint,2,opt,name=op,proto3,enum=aggregator.MessageOp" json:"op,omitempty"`
	TaskMetadata  *SyncMessagesResp_TaskMetadata `protobuf:"bytes,3,opt,name=task_metadata,json=taskMetadata,proto3" json:"task_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessagesResp) Reset() {
	*x = SyncMessagesResp{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessagesResp) ProtoMessage() {}

func (x *SyncMessagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessagesResp.ProtoReflect.Descriptor instead.
func (*SyncMessagesResp) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *SyncMessagesResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncMessagesResp) GetOp() MessageOp {
	if x != nil {
		return x.Op
	}
	return MessageOp_Unset
}

func (x *SyncMessagesResp) GetTaskMetadata() *SyncMessagesResp_TaskMetadata {
	if x != nil {
		return x.TaskMetadata
	}
	return nil
}

type AckMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessageReq) Reset() {
	*x = AckMessageReq{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageReq) ProtoMessage() {}

func (x *AckMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageReq.ProtoReflect.Descriptor instead.
func (*AckMessageReq) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *AckMessageReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NotifyTriggersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        *TriggerReason         `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyTriggersReq) Reset() {
	*x = NotifyTriggersReq{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyTriggersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTriggersReq) ProtoMessage() {}

func (x *NotifyTriggersReq) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTriggersReq.ProtoReflect.Descriptor instead.
func (*NotifyTriggersReq) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyTriggersReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NotifyTriggersReq) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *NotifyTriggersReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *NotifyTriggersReq) GetReason() *TriggerReason {
	if x != nil {
		return x.Reason
	}
	return nil
}

type NotifyTriggersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyTriggersResp) Reset() {
	*x = NotifyTriggersResp{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyTriggersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTriggersResp) ProtoMessage() {}

func (x *NotifyTriggersResp) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTriggersResp.ProtoReflect.Descriptor instead.
func (*NotifyTriggersResp) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *NotifyTriggersResp) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Checkin_Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uptime        int64                  `protobuf:"varint,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	QueueDepth    int64                  `protobuf:"varint,2,opt,name=queueDepth,proto3" json:"queueDepth,omitempty"`
	LastHeartbeat *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkin_Status) Reset() {
	*x = Checkin_Status{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkin_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkin_Status) ProtoMessage() {}

func (x *Checkin_Status) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkin_Status.ProtoReflect.Descriptor instead.
func (*Checkin_Status) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Checkin_Status) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *Checkin_Status) GetQueueDepth() int64 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *Checkin_Status) GetLastHeartbeat() *timestamp.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

type SyncMessagesResp_TaskMetadata struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// how many time this task can run
	Remain        int64        `protobuf:"varint,2,opt,name=remain,proto3" json:"remain,omitempty"`
	ExpiredAt     int64        `protobuf:"varint,3,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	Trigger       *TaskTrigger `protobuf:"bytes,4,opt,name=trigger,proto3" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessagesResp_TaskMetadata) Reset() {
	*x = SyncMessagesResp_TaskMetadata{}
	mi := &file_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessagesResp_TaskMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessagesResp_TaskMetadata) ProtoMessage() {}

func (x *SyncMessagesResp_TaskMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessagesResp_TaskMetadata.ProtoReflect.Descriptor instead.
func (*SyncMessagesResp_TaskMetadata) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SyncMessagesResp_TaskMetadata) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SyncMessagesResp_TaskMetadata) GetRemain() int64 {
	if x != nil {
		return x.Remain
	}
	return 0
}

func (x *SyncMessagesResp_TaskMetadata) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *SyncMessagesResp_TaskMetadata) GetTrigger() *TaskTrigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\n" +
	"aggregator\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\tavs.proto\"\xa7\x03\n" +
	"\aCheckin\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x122\n" +
	"\x06status\x18\x04 \x01(\v2\x1a.aggregator.Checkin.StatusR\x06status\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12 \n" +
	"\vmetricsPort\x18\x06 \x01(\x05R\vmetricsPort\x12\x1a\n" +
	"\bremoteIP\x18\a \x01(\tR\bremoteIP\x12!\n" +
	"\fblock_number\x18\b \x01(\x03R\vblockNumber\x12\x1f\n" +
	"\vevent_count\x18\t \x01(\x03R\n" +
	"eventCount\x1a\x83\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x06uptime\x18\x01 \x01(\x03R\x06uptime\x12\x1e\n" +
	"\n" +
	"queueDepth\x18\x02 \x01(\x03R\n" +
	"queueDepth\x12A\n" +
	"\x0elast_heartbeat\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\"H\n" +
	"\vCheckinResp\x129\n" +
	"\n" +
	"updated_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x82\x01\n" +
	"\x0fSyncMessagesReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12'\n" +
	"\x0fmonotonic_clock\x18\x04 \x01(\x03R\x0emonotonicClock\"\xad\x02\n" +
	"\x10SyncMessagesResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x02op\x18\x02 \x01(\x0e2\x15.aggregator.MessageOpR\x02op\x12N\n" +
	"\rtask_metadata\x18\x03 \x01(\v2).aggregator.SyncMessagesResp.TaskMetadataR\ftaskMetadata\x1a\x91\x01\n" +
	"\fTaskMetadata\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06remain\x18\x02 \x01(\x03R\x06remain\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x03 \x01(\x03R\texpiredAt\x121\n" +
	"\atrigger\x18\x04 \x01(\v2\x17.aggregator.TaskTriggerR\atrigger\"\x1f\n" +
	"\rAckMessageReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x97\x01\n" +
	"\x11NotifyTriggersReq\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x121\n" +
	"\x06reason\x18\x04 \x01(\v2\x19.aggregator.TriggerReasonR\x06reason\"O\n" +
	"\x12NotifyTriggersResp\x129\n" +
	"\n" +
	"updated_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*a\n" +
	"\tMessageOp\x12\t\n" +
	"\x05Unset\x10\x00\x12\x16\n" +
	"\x12MonitorTaskTrigger\x10\x01\x12\x0e\n" +
	"\n" +
	"CancelTask\x10\x02\x12\x0e\n" +
	"\n" +
	"DeleteTask\x10\x03\x12\x11\n" +
	"\rCompletedTask\x10\x042\xa0\x02\n" +
	"\x04Node\x126\n" +
	"\x04Ping\x12\x13.aggregator.Checkin\x1a\x17.aggregator.CheckinResp\"\x00\x12M\n" +
	"\fSyncMessages\x12\x1b.aggregator.SyncMessagesReq\x1a\x1c.aggregator.SyncMessagesResp\"\x000\x01\x12>\n" +
	"\x03Ack\x12\x19.aggregator.AckMessageReq\x1a\x1a.google.protobuf.BoolValue\"\x00\x12Q\n" +
	"\x0eNotifyTriggers\x12\x1d.aggregator.NotifyTriggersReq\x1a\x1e.aggregator.NotifyTriggersResp\"\x00B\fZ\n" +
	"./avsprotob\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_node_proto_goTypes = []any{
	(MessageOp)(0),                        // 0: aggregator.MessageOp
	(*Checkin)(nil),                       // 1: aggregator.Checkin
	(*CheckinResp)(nil),                   // 2: aggregator.CheckinResp
	(*SyncMessagesReq)(nil),               // 3: aggregator.SyncMessagesReq
	(*SyncMessagesResp)(nil),              // 4: aggregator.SyncMessagesResp
	(*AckMessageReq)(nil),                 // 5: aggregator.AckMessageReq
	(*NotifyTriggersReq)(nil),             // 6: aggregator.NotifyTriggersReq
	(*NotifyTriggersResp)(nil),            // 7: aggregator.NotifyTriggersResp
	(*Checkin_Status)(nil),                // 8: aggregator.Checkin.Status
	(*SyncMessagesResp_TaskMetadata)(nil), // 9: aggregator.SyncMessagesResp.TaskMetadata
	(*timestamp.Timestamp)(nil),           // 10: google.protobuf.Timestamp
	(*TriggerReason)(nil),                 // 11: aggregator.TriggerReason
	(*TaskTrigger)(nil),                   // 12: aggregator.TaskTrigger
	(*wrappers.BoolValue)(nil),            // 13: google.protobuf.BoolValue
}
var file_node_proto_depIdxs = []int32{
	8,  // 0: aggregator.Checkin.status:type_name -> aggregator.Checkin.Status
	10, // 1: aggregator.CheckinResp.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: aggregator.SyncMessagesResp.op:type_name -> aggregator.MessageOp
	9,  // 3: aggregator.SyncMessagesResp.task_metadata:type_name -> aggregator.SyncMessagesResp.TaskMetadata
	11, // 4: aggregator.NotifyTriggersReq.reason:type_name -> aggregator.TriggerReason
	10, // 5: aggregator.NotifyTriggersResp.updated_at:type_name -> google.protobuf.Timestamp
	10, // 6: aggregator.Checkin.Status.last_heartbeat:type_name -> google.protobuf.Timestamp
	12, // 7: aggregator.SyncMessagesResp.TaskMetadata.trigger:type_name -> aggregator.TaskTrigger
	1,  // 8: aggregator.Node.Ping:input_type -> aggregator.Checkin
	3,  // 9: aggregator.Node.SyncMessages:input_type -> aggregator.SyncMessagesReq
	5,  // 10: aggregator.Node.Ack:input_type -> aggregator.AckMessageReq
	6,  // 11: aggregator.Node.NotifyTriggers:input_type -> aggregator.NotifyTriggersReq
	2,  // 12: aggregator.Node.Ping:output_type -> aggregator.CheckinResp
	4,  // 13: aggregator.Node.SyncMessages:output_type -> aggregator.SyncMessagesResp
	13, // 14: aggregator.Node.Ack:output_type -> google.protobuf.BoolValue
	7,  // 15: aggregator.Node.NotifyTriggers:output_type -> aggregator.NotifyTriggersResp
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_avs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		EnumInfos:         file_node_proto_enumTypes,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
