// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: worker.proto

package avsproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health check
type WorkerHealthCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHealthCheckReq) Reset() {
	*x = WorkerHealthCheckReq{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHealthCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHealthCheckReq) ProtoMessage() {}

func (x *WorkerHealthCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHealthCheckReq.ProtoReflect.Descriptor instead.
func (*WorkerHealthCheckReq) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

type WorkerHealthCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "OK", "DEGRADED", etc.
	ChainId       int64                  `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainName     string                 `protobuf:"bytes,3,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	LatestBlock   int64                  `protobuf:"varint,4,opt,name=latest_block,json=latestBlock,proto3" json:"latest_block,omitempty"` // Latest block number from chain RPC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHealthCheckResp) Reset() {
	*x = WorkerHealthCheckResp{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHealthCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHealthCheckResp) ProtoMessage() {}

func (x *WorkerHealthCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHealthCheckResp.ProtoReflect.Descriptor instead.
func (*WorkerHealthCheckResp) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerHealthCheckResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkerHealthCheckResp) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *WorkerHealthCheckResp) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *WorkerHealthCheckResp) GetLatestBlock() int64 {
	if x != nil {
		return x.LatestBlock
	}
	return 0
}

// UserOp execution
type ExecuteUserOpReq struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Owner              string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`                                                       // Owner EOA address (hex)
	CallData           []byte                 `protobuf:"bytes,2,opt,name=call_data,json=callData,proto3" json:"call_data,omitempty"`                                 // Encoded calldata for execute/executeBatch
	SmartWalletAddress string                 `protobuf:"bytes,3,opt,name=smart_wallet_address,json=smartWalletAddress,proto3" json:"smart_wallet_address,omitempty"` // Smart wallet address override (hex, optional)
	UsePaymaster       bool                   `protobuf:"varint,4,opt,name=use_paymaster,json=usePaymaster,proto3" json:"use_paymaster,omitempty"`                    // Whether to use paymaster for gas sponsorship
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecuteUserOpReq) Reset() {
	*x = ExecuteUserOpReq{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteUserOpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteUserOpReq) ProtoMessage() {}

func (x *ExecuteUserOpReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteUserOpReq.ProtoReflect.Descriptor instead.
func (*ExecuteUserOpReq) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteUserOpReq) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ExecuteUserOpReq) GetCallData() []byte {
	if x != nil {
		return x.CallData
	}
	return nil
}

func (x *ExecuteUserOpReq) GetSmartWalletAddress() string {
	if x != nil {
		return x.SmartWalletAddress
	}
	return ""
}

func (x *ExecuteUserOpReq) GetUsePaymaster() bool {
	if x != nil {
		return x.UsePaymaster
	}
	return false
}

type ExecuteUserOpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`               // On-chain transaction hash
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                               // Error message if failed
	UserOpHash    string                 `protobuf:"bytes,4,opt,name=user_op_hash,json=userOpHash,proto3" json:"user_op_hash,omitempty"` // ERC-4337 UserOp hash
	GasUsed       uint64                 `protobuf:"varint,5,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	GasCostWei    string                 `protobuf:"bytes,6,opt,name=gas_cost_wei,json=gasCostWei,proto3" json:"gas_cost_wei,omitempty"` // Total gas cost in wei (big.Int as string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteUserOpResp) Reset() {
	*x = ExecuteUserOpResp{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteUserOpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteUserOpResp) ProtoMessage() {}

func (x *ExecuteUserOpResp) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteUserOpResp.ProtoReflect.Descriptor instead.
func (*ExecuteUserOpResp) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteUserOpResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteUserOpResp) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ExecuteUserOpResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteUserOpResp) GetUserOpHash() string {
	if x != nil {
		return x.UserOpHash
	}
	return ""
}

func (x *ExecuteUserOpResp) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ExecuteUserOpResp) GetGasCostWei() string {
	if x != nil {
		return x.GasCostWei
	}
	return ""
}

// Nonce query
type WorkerGetNonceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"` // Owner EOA address (hex)
	Salt          int64                  `protobuf:"varint,2,opt,name=salt,proto3" json:"salt,omitempty"`  // Key/salt for nonce space
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerGetNonceReq) Reset() {
	*x = WorkerGetNonceReq{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerGetNonceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerGetNonceReq) ProtoMessage() {}

func (x *WorkerGetNonceReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerGetNonceReq.ProtoReflect.Descriptor instead.
func (*WorkerGetNonceReq) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerGetNonceReq) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *WorkerGetNonceReq) GetSalt() int64 {
	if x != nil {
		return x.Salt
	}
	return 0
}

type WorkerGetNonceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"` // big.Int as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerGetNonceResp) Reset() {
	*x = WorkerGetNonceResp{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerGetNonceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerGetNonceResp) ProtoMessage() {}

func (x *WorkerGetNonceResp) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerGetNonceResp.ProtoReflect.Descriptor instead.
func (*WorkerGetNonceResp) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *WorkerGetNonceResp) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

// Smart wallet address derivation
type WorkerGetSmartWalletAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"` // Owner EOA address (hex)
	Salt          int64                  `protobuf:"varint,2,opt,name=salt,proto3" json:"salt,omitempty"`  // Salt for CREATE2 derivation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerGetSmartWalletAddressReq) Reset() {
	*x = WorkerGetSmartWalletAddressReq{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerGetSmartWalletAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerGetSmartWalletAddressReq) ProtoMessage() {}

func (x *WorkerGetSmartWalletAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerGetSmartWalletAddressReq.ProtoReflect.Descriptor instead.
func (*WorkerGetSmartWalletAddressReq) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *WorkerGetSmartWalletAddressReq) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *WorkerGetSmartWalletAddressReq) GetSalt() int64 {
	if x != nil {
		return x.Salt
	}
	return 0
}

type WorkerGetSmartWalletAddressResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // Derived smart wallet address (hex)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerGetSmartWalletAddressResp) Reset() {
	*x = WorkerGetSmartWalletAddressResp{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerGetSmartWalletAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerGetSmartWalletAddressResp) ProtoMessage() {}

func (x *WorkerGetSmartWalletAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerGetSmartWalletAddressResp.ProtoReflect.Descriptor instead.
func (*WorkerGetSmartWalletAddressResp) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

func (x *WorkerGetSmartWalletAddressResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Token metadata enrichment
type WorkerGetTokenMetadataReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC20 token contract address (hex)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkerGetTokenMetadataReq) Reset() {
	*x = WorkerGetTokenMetadataReq{}
	mi := &file_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerGetTokenMetadataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerGetTokenMetadataReq) ProtoMessage() {}

func (x *WorkerGetTokenMetadataReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerGetTokenMetadataReq.ProtoReflect.Descriptor instead.
func (*WorkerGetTokenMetadataReq) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{8}
}

func (x *WorkerGetTokenMetadataReq) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

type WorkerGetTokenMetadataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals      uint32                 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Found         bool                   `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`  // Whether the token was found
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"` // "whitelist", "rpc", or "native"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerGetTokenMetadataResp) Reset() {
	*x = WorkerGetTokenMetadataResp{}
	mi := &file_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerGetTokenMetadataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerGetTokenMetadataResp) ProtoMessage() {}

func (x *WorkerGetTokenMetadataResp) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerGetTokenMetadataResp.ProtoReflect.Descriptor instead.
func (*WorkerGetTokenMetadataResp) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{9}
}

func (x *WorkerGetTokenMetadataResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkerGetTokenMetadataResp) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *WorkerGetTokenMetadataResp) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *WorkerGetTokenMetadataResp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *WorkerGetTokenMetadataResp) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// Nonce query by smart wallet address (companion to GetNonce-by-owner)
type WorkerGetNonceByAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"` // Smart wallet address (hex)
	NonceKey      string                 `protobuf:"bytes,2,opt,name=nonce_key,json=nonceKey,proto3" json:"nonce_key,omitempty"`                // 192-bit key for the EntryPoint nonce space
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerGetNonceByAddressReq) Reset() {
	*x = WorkerGetNonceByAddressReq{}
	mi := &file_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerGetNonceByAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerGetNonceByAddressReq) ProtoMessage() {}

func (x *WorkerGetNonceByAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerGetNonceByAddressReq.ProtoReflect.Descriptor instead.
func (*WorkerGetNonceByAddressReq) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{10}
}

func (x *WorkerGetNonceByAddressReq) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *WorkerGetNonceByAddressReq) GetNonceKey() string {
	if x != nil {
		return x.NonceKey
	}
	return ""
}

// Gas price
type WorkerSuggestGasPriceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerSuggestGasPriceReq) Reset() {
	*x = WorkerSuggestGasPriceReq{}
	mi := &file_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerSuggestGasPriceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerSuggestGasPriceReq) ProtoMessage() {}

func (x *WorkerSuggestGasPriceReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerSuggestGasPriceReq.ProtoReflect.Descriptor instead.
func (*WorkerSuggestGasPriceReq) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{11}
}

type WorkerSuggestGasPriceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GasPriceWei   string                 `protobuf:"bytes,1,opt,name=gas_price_wei,json=gasPriceWei,proto3" json:"gas_price_wei,omitempty"` // big.Int as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerSuggestGasPriceResp) Reset() {
	*x = WorkerSuggestGasPriceResp{}
	mi := &file_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerSuggestGasPriceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerSuggestGasPriceResp) ProtoMessage() {}

func (x *WorkerSuggestGasPriceResp) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerSuggestGasPriceResp.ProtoReflect.Descriptor instead.
func (*WorkerSuggestGasPriceResp) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{12}
}

func (x *WorkerSuggestGasPriceResp) GetGasPriceWei() string {
	if x != nil {
		return x.GasPriceWei
	}
	return ""
}

// Gas estimate (mirrors ethereum.CallMsg fields the estimator uses)
type WorkerEstimateGasReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`   // Sender (hex). Optional; chain default if empty.
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`       // Destination contract (hex).
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // Wei (big.Int as string); empty/zero for no value.
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`   // Calldata.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerEstimateGasReq) Reset() {
	*x = WorkerEstimateGasReq{}
	mi := &file_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerEstimateGasReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerEstimateGasReq) ProtoMessage() {}

func (x *WorkerEstimateGasReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerEstimateGasReq.ProtoReflect.Descriptor instead.
func (*WorkerEstimateGasReq) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{13}
}

func (x *WorkerEstimateGasReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *WorkerEstimateGasReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *WorkerEstimateGasReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *WorkerEstimateGasReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WorkerEstimateGasResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gas           uint64                 `protobuf:"varint,1,opt,name=gas,proto3" json:"gas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerEstimateGasResp) Reset() {
	*x = WorkerEstimateGasResp{}
	mi := &file_worker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerEstimateGasResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerEstimateGasResp) ProtoMessage() {}

func (x *WorkerEstimateGasResp) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerEstimateGasResp.ProtoReflect.Descriptor instead.
func (*WorkerEstimateGasResp) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{14}
}

func (x *WorkerEstimateGasResp) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

// CodeAt
type WorkerGetCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // Contract address (hex).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerGetCodeReq) Reset() {
	*x = WorkerGetCodeReq{}
	mi := &file_worker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerGetCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerGetCodeReq) ProtoMessage() {}

func (x *WorkerGetCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerGetCodeReq.ProtoReflect.Descriptor instead.
func (*WorkerGetCodeReq) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{15}
}

func (x *WorkerGetCodeReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type WorkerGetCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          []byte                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // Raw bytecode (empty if not deployed).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerGetCodeResp) Reset() {
	*x = WorkerGetCodeResp{}
	mi := &file_worker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerGetCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerGetCodeResp) ProtoMessage() {}

func (x *WorkerGetCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerGetCodeResp.ProtoReflect.Descriptor instead.
func (*WorkerGetCodeResp) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{16}
}

func (x *WorkerGetCodeResp) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

// Native-coin balance
type WorkerGetBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // Account address (hex).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerGetBalanceReq) Reset() {
	*x = WorkerGetBalanceReq{}
	mi := &file_worker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerGetBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerGetBalanceReq) ProtoMessage() {}

func (x *WorkerGetBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerGetBalanceReq.ProtoReflect.Descriptor instead.
func (*WorkerGetBalanceReq) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{17}
}

func (x *WorkerGetBalanceReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type WorkerGetBalanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BalanceWei    string                 `protobuf:"bytes,1,opt,name=balance_wei,json=balanceWei,proto3" json:"balance_wei,omitempty"` // Native balance in wei (big.Int as string).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerGetBalanceResp) Reset() {
	*x = WorkerGetBalanceResp{}
	mi := &file_worker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerGetBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerGetBalanceResp) ProtoMessage() {}

func (x *WorkerGetBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerGetBalanceResp.ProtoReflect.Descriptor instead.
func (*WorkerGetBalanceResp) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{18}
}

func (x *WorkerGetBalanceResp) GetBalanceWei() string {
	if x != nil {
		return x.BalanceWei
	}
	return ""
}

// ERC-20 token balance
type WorkerGetTokenBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"` // ERC-20 contract address (hex).
	OwnerAddress  string                 `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"` // Balance holder address (hex).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerGetTokenBalanceReq) Reset() {
	*x = WorkerGetTokenBalanceReq{}
	mi := &file_worker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerGetTokenBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerGetTokenBalanceReq) ProtoMessage() {}

func (x *WorkerGetTokenBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerGetTokenBalanceReq.ProtoReflect.Descriptor instead.
func (*WorkerGetTokenBalanceReq) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{19}
}

func (x *WorkerGetTokenBalanceReq) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *WorkerGetTokenBalanceReq) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

type WorkerGetTokenBalanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       string                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"` // Raw token balance (big.Int as string, no decimals applied).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerGetTokenBalanceResp) Reset() {
	*x = WorkerGetTokenBalanceResp{}
	mi := &file_worker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerGetTokenBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerGetTokenBalanceResp) ProtoMessage() {}

func (x *WorkerGetTokenBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerGetTokenBalanceResp.ProtoReflect.Descriptor instead.
func (*WorkerGetTokenBalanceResp) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{20}
}

func (x *WorkerGetTokenBalanceResp) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\n" +
	"aggregator\"\x16\n" +
	"\x14WorkerHealthCheckReq\"\x8c\x01\n" +
	"\x15WorkerHealthCheckResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x03R\achainId\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x03 \x01(\tR\tchainName\x12!\n" +
	"\flatest_block\x18\x04 \x01(\x03R\vlatestBlock\"\x9c\x01\n" +
	"\x10ExecuteUserOpReq\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x1b\n" +
	"\tcall_data\x18\x02 \x01(\fR\bcallData\x120\n" +
	"\x14smart_wallet_address\x18\x03 \x01(\tR\x12smartWalletAddress\x12#\n" +
	"\ruse_paymaster\x18\x04 \x01(\bR\fusePaymaster\"\xbb\x01\n" +
	"\x11ExecuteUserOpResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12 \n" +
	"\fuser_op_hash\x18\x04 \x01(\tR\n" +
	"userOpHash\x12\x19\n" +
	"\bgas_used\x18\x05 \x01(\x04R\agasUsed\x12 \n" +
	"\fgas_cost_wei\x18\x06 \x01(\tR\n" +
	"gasCostWei\"=\n" +
	"\x11WorkerGetNonceReq\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\x03R\x04salt\"*\n" +
	"\x12WorkerGetNonceResp\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\"J\n" +
	"\x1eWorkerGetSmartWalletAddressReq\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\x03R\x04salt\";\n" +
	"\x1fWorkerGetSmartWalletAddressResp\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"F\n" +
	"\x19WorkerGetTokenMetadataReq\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\"\x92\x01\n" +
	"\x1aWorkerGetTokenMetadataResp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\rR\bdecimals\x12\x14\n" +
	"\x05found\x18\x04 \x01(\bR\x05found\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"`\n" +
	"\x1aWorkerGetNonceByAddressReq\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12\x1b\n" +
	"\tnonce_key\x18\x02 \x01(\tR\bnonceKey\"\x1a\n" +
	"\x18WorkerSuggestGasPriceReq\"?\n" +
	"\x19WorkerSuggestGasPriceResp\x12\"\n" +
	"\rgas_price_wei\x18\x01 \x01(\tR\vgasPriceWei\"d\n" +
	"\x14WorkerEstimateGasReq\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\")\n" +
	"\x15WorkerEstimateGasResp\x12\x10\n" +
	"\x03gas\x18\x01 \x01(\x04R\x03gas\",\n" +
	"\x10WorkerGetCodeReq\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"'\n" +
	"\x11WorkerGetCodeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\fR\x04code\"/\n" +
	"\x13WorkerGetBalanceReq\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"7\n" +
	"\x14WorkerGetBalanceResp\x12\x1f\n" +
	"\vbalance_wei\x18\x01 \x01(\tR\n" +
	"balanceWei\"d\n" +
	"\x18WorkerGetTokenBalanceReq\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12#\n" +
	"\rowner_address\x18\x02 \x01(\tR\fownerAddress\"5\n" +
	"\x19WorkerGetTokenBalanceResp\x12\x18\n" +
	"\abalance\x18\x01 \x01(\tR\abalance2\xdf\a\n" +
	"\vChainWorker\x12X\n" +
	"\x11WorkerHealthCheck\x12 .aggregator.WorkerHealthCheckReq\x1a!.aggregator.WorkerHealthCheckResp\x12L\n" +
	"\rExecuteUserOp\x12\x1c.aggregator.ExecuteUserOpReq\x1a\x1d.aggregator.ExecuteUserOpResp\x12I\n" +
	"\bGetNonce\x12\x1d.aggregator.WorkerGetNonceReq\x1a\x1e.aggregator.WorkerGetNonceResp\x12p\n" +
	"\x15GetSmartWalletAddress\x12*.aggregator.WorkerGetSmartWalletAddressReq\x1a+.aggregator.WorkerGetSmartWalletAddressResp\x12a\n" +
	"\x10GetTokenMetadata\x12%.aggregator.WorkerGetTokenMetadataReq\x1a&.aggregator.WorkerGetTokenMetadataResp\x12[\n" +
	"\x11GetNonceByAddress\x12&.aggregator.WorkerGetNonceByAddressReq\x1a\x1e.aggregator.WorkerGetNonceResp\x12^\n" +
	"\x0fSuggestGasPrice\x12$.aggregator.WorkerSuggestGasPriceReq\x1a%.aggregator.WorkerSuggestGasPriceResp\x12R\n" +
	"\vEstimateGas\x12 .aggregator.WorkerEstimateGasReq\x1a!.aggregator.WorkerEstimateGasResp\x12F\n" +
	"\aGetCode\x12\x1c.aggregator.WorkerGetCodeReq\x1a\x1d.aggregator.WorkerGetCodeResp\x12O\n" +
	"\n" +
	"GetBalance\x12\x1f.aggregator.WorkerGetBalanceReq\x1a .aggregator.WorkerGetBalanceResp\x12^\n" +
	"\x0fGetTokenBalance\x12$.aggregator.WorkerGetTokenBalanceReq\x1a%.aggregator.WorkerGetTokenBalanceRespB\fZ\n" +
	"./avsprotob\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_worker_proto_goTypes = []any{
	(*WorkerHealthCheckReq)(nil),            // 0: aggregator.WorkerHealthCheckReq
	(*WorkerHealthCheckResp)(nil),           // 1: aggregator.WorkerHealthCheckResp
	(*ExecuteUserOpReq)(nil),                // 2: aggregator.ExecuteUserOpReq
	(*ExecuteUserOpResp)(nil),               // 3: aggregator.ExecuteUserOpResp
	(*WorkerGetNonceReq)(nil),               // 4: aggregator.WorkerGetNonceReq
	(*WorkerGetNonceResp)(nil),              // 5: aggregator.WorkerGetNonceResp
	(*WorkerGetSmartWalletAddressReq)(nil),  // 6: aggregator.WorkerGetSmartWalletAddressReq
	(*WorkerGetSmartWalletAddressResp)(nil), // 7: aggregator.WorkerGetSmartWalletAddressResp
	(*WorkerGetTokenMetadataReq)(nil),       // 8: aggregator.WorkerGetTokenMetadataReq
	(*WorkerGetTokenMetadataResp)(nil),      // 9: aggregator.WorkerGetTokenMetadataResp
	(*WorkerGetNonceByAddressReq)(nil),      // 10: aggregator.WorkerGetNonceByAddressReq
	(*WorkerSuggestGasPriceReq)(nil),        // 11: aggregator.WorkerSuggestGasPriceReq
	(*WorkerSuggestGasPriceResp)(nil),       // 12: aggregator.WorkerSuggestGasPriceResp
	(*WorkerEstimateGasReq)(nil),            // 13: aggregator.WorkerEstimateGasReq
	(*WorkerEstimateGasResp)(nil),           // 14: aggregator.WorkerEstimateGasResp
	(*WorkerGetCodeReq)(nil),                // 15: aggregator.WorkerGetCodeReq
	(*WorkerGetCodeResp)(nil),               // 16: aggregator.WorkerGetCodeResp
	(*WorkerGetBalanceReq)(nil),             // 17: aggregator.WorkerGetBalanceReq
	(*WorkerGetBalanceResp)(nil),            // 18: aggregator.WorkerGetBalanceResp
	(*WorkerGetTokenBalanceReq)(nil),        // 19: aggregator.WorkerGetTokenBalanceReq
	(*WorkerGetTokenBalanceResp)(nil),       // 20: aggregator.WorkerGetTokenBalanceResp
}
var file_worker_proto_depIdxs = []int32{
	0,  // 0: aggregator.ChainWorker.WorkerHealthCheck:input_type -> aggregator.WorkerHealthCheckReq
	2,  // 1: aggregator.ChainWorker.ExecuteUserOp:input_type -> aggregator.ExecuteUserOpReq
	4,  // 2: aggregator.ChainWorker.GetNonce:input_type -> aggregator.WorkerGetNonceReq
	6,  // 3: aggregator.ChainWorker.GetSmartWalletAddress:input_type -> aggregator.WorkerGetSmartWalletAddressReq
	8,  // 4: aggregator.ChainWorker.GetTokenMetadata:input_type -> aggregator.WorkerGetTokenMetadataReq
	10, // 5: aggregator.ChainWorker.GetNonceByAddress:input_type -> aggregator.WorkerGetNonceByAddressReq
	11, // 6: aggregator.ChainWorker.SuggestGasPrice:input_type -> aggregator.WorkerSuggestGasPriceReq
	13, // 7: aggregator.ChainWorker.EstimateGas:input_type -> aggregator.WorkerEstimateGasReq
	15, // 8: aggregator.ChainWorker.GetCode:input_type -> aggregator.WorkerGetCodeReq
	17, // 9: aggregator.ChainWorker.GetBalance:input_type -> aggregator.WorkerGetBalanceReq
	19, // 10: aggregator.ChainWorker.GetTokenBalance:input_type -> aggregator.WorkerGetTokenBalanceReq
	1,  // 11: aggregator.ChainWorker.WorkerHealthCheck:output_type -> aggregator.WorkerHealthCheckResp
	3,  // 12: aggregator.ChainWorker.ExecuteUserOp:output_type -> aggregator.ExecuteUserOpResp
	5,  // 13: aggregator.ChainWorker.GetNonce:output_type -> aggregator.WorkerGetNonceResp
	7,  // 14: aggregator.ChainWorker.GetSmartWalletAddress:output_type -> aggregator.WorkerGetSmartWalletAddressResp
	9,  // 15: aggregator.ChainWorker.GetTokenMetadata:output_type -> aggregator.WorkerGetTokenMetadataResp
	5,  // 16: aggregator.ChainWorker.GetNonceByAddress:output_type -> aggregator.WorkerGetNonceResp
	12, // 17: aggregator.ChainWorker.SuggestGasPrice:output_type -> aggregator.WorkerSuggestGasPriceResp
	14, // 18: aggregator.ChainWorker.EstimateGas:output_type -> aggregator.WorkerEstimateGasResp
	16, // 19: aggregator.ChainWorker.GetCode:output_type -> aggregator.WorkerGetCodeResp
	18, // 20: aggregator.ChainWorker.GetBalance:output_type -> aggregator.WorkerGetBalanceResp
	20, // 21: aggregator.ChainWorker.GetTokenBalance:output_type -> aggregator.WorkerGetTokenBalanceResp
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
