// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: worker.proto

package avsproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChainWorker_WorkerHealthCheck_FullMethodName      = "/aggregator.ChainWorker/WorkerHealthCheck"
	ChainWorker_ExecuteUserOp_FullMethodName          = "/aggregator.ChainWorker/ExecuteUserOp"
	ChainWorker_GetNonce_FullMethodName               = "/aggregator.ChainWorker/GetNonce"
	ChainWorker_GetSmartWalletAddress_FullMethodName  = "/aggregator.ChainWorker/GetSmartWalletAddress"
	ChainWorker_GetTokenMetadata_FullMethodName       = "/aggregator.ChainWorker/GetTokenMetadata"
	ChainWorker_GetNonceByAddress_FullMethodName      = "/aggregator.ChainWorker/GetNonceByAddress"
	ChainWorker_SuggestGasPrice_FullMethodName        = "/aggregator.ChainWorker/SuggestGasPrice"
	ChainWorker_EstimateGas_FullMethodName            = "/aggregator.ChainWorker/EstimateGas"
	ChainWorker_GetCode_FullMethodName                = "/aggregator.ChainWorker/GetCode"
	ChainWorker_GetBalance_FullMethodName             = "/aggregator.ChainWorker/GetBalance"
	ChainWorker_GetTokenBalance_FullMethodName        = "/aggregator.ChainWorker/GetTokenBalance"
	ChainWorker_CallContract_FullMethodName           = "/aggregator.ChainWorker/CallContract"
	ChainWorker_GetBlockHeader_FullMethodName         = "/aggregator.ChainWorker/GetBlockHeader"
	ChainWorker_GetBlockNumber_FullMethodName         = "/aggregator.ChainWorker/GetBlockNumber"
	ChainWorker_FindMatchingWalletSalt_FullMethodName = "/aggregator.ChainWorker/FindMatchingWalletSalt"
	ChainWorker_GetTransactionReceipt_FullMethodName  = "/aggregator.ChainWorker/GetTransactionReceipt"
)

// ChainWorkerClient is the client API for ChainWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChainWorker is the internal gRPC service running on each chain worker.
// The gateway connects to workers by chain_id using addresses from config.
// Workers handle chain-specific operations: UserOp execution, nonce queries,
// smart wallet derivation, token enrichment, and gas estimation.
type ChainWorkerClient interface {
	// Health check - gateway verifies worker connectivity and chain status
	WorkerHealthCheck(ctx context.Context, in *WorkerHealthCheckReq, opts ...grpc.CallOption) (*WorkerHealthCheckResp, error)
	// Execute a UserOp on this chain via the bundler
	ExecuteUserOp(ctx context.Context, in *ExecuteUserOpReq, opts ...grpc.CallOption) (*ExecuteUserOpResp, error)
	// Get the nonce for a smart wallet on this chain
	GetNonce(ctx context.Context, in *WorkerGetNonceReq, opts ...grpc.CallOption) (*WorkerGetNonceResp, error)
	// Get the smart wallet address for an owner on this chain
	GetSmartWalletAddress(ctx context.Context, in *WorkerGetSmartWalletAddressReq, opts ...grpc.CallOption) (*WorkerGetSmartWalletAddressResp, error)
	// Get token metadata (enrichment) for a contract address on this chain
	GetTokenMetadata(ctx context.Context, in *WorkerGetTokenMetadataReq, opts ...grpc.CallOption) (*WorkerGetTokenMetadataResp, error)
	// Get the nonce for an arbitrary smart wallet address on this chain.
	// Differs from GetNonce in that the caller already knows the wallet
	// address (looked up from gateway storage) and doesn't want to re-derive
	// it from (owner, salt). Used by REST handlers that read the nonce
	// directly off the EntryPoint contract.
	GetNonceByAddress(ctx context.Context, in *WorkerGetNonceByAddressReq, opts ...grpc.CallOption) (*WorkerGetNonceResp, error)
	// Suggest a gas price for this chain. Wraps ethclient.SuggestGasPrice.
	// Used by the fee estimator to price UserOps.
	SuggestGasPrice(ctx context.Context, in *WorkerSuggestGasPriceReq, opts ...grpc.CallOption) (*WorkerSuggestGasPriceResp, error)
	// Estimate gas for a contract call on this chain. Wraps
	// ethclient.EstimateGas with the same CallMsg shape ethclient takes.
	// Used by the fee estimator to gas-budget UserOp executions.
	EstimateGas(ctx context.Context, in *WorkerEstimateGasReq, opts ...grpc.CallOption) (*WorkerEstimateGasResp, error)
	// Read the bytecode at a contract address. Wraps ethclient.CodeAt.
	// Used by the fee estimator to detect whether the runner contract is
	// deployed before issuing UserOps against it.
	GetCode(ctx context.Context, in *WorkerGetCodeReq, opts ...grpc.CallOption) (*WorkerGetCodeResp, error)
	// Read the native-coin balance (wei) at an address. Wraps
	// ethclient.BalanceAt(latest). Used by the gateway's withdraw preflight
	// to validate / size native-token withdrawals.
	GetBalance(ctx context.Context, in *WorkerGetBalanceReq, opts ...grpc.CallOption) (*WorkerGetBalanceResp, error)
	// Read an ERC-20 token balance for an owner. Wraps erc20.BalanceOf.
	// Used by the gateway's withdraw preflight to validate / size ERC-20
	// withdrawals.
	GetTokenBalance(ctx context.Context, in *WorkerGetTokenBalanceReq, opts ...grpc.CallOption) (*WorkerGetTokenBalanceResp, error)
	// Execute a read-only contract call (eth_call) on this chain. Wraps
	// ethclient.CallContract. Used by the contractRead node so the gateway
	// issues no direct eth_call against execution chains.
	CallContract(ctx context.Context, in *WorkerCallContractReq, opts ...grpc.CallOption) (*WorkerCallContractResp, error)
	// Read a block header's number, hash, and timestamp. Wraps
	// ethclient.HeaderByNumber. Used to stamp simulation receipts and
	// enrich event timestamps without a gateway-side chain dial.
	GetBlockHeader(ctx context.Context, in *WorkerGetBlockHeaderReq, opts ...grpc.CallOption) (*WorkerGetBlockHeaderResp, error)
	// Read the latest block number. Wraps ethclient.BlockNumber. Used by the
	// immediate-trigger path to stamp the current block for the operator.
	GetBlockNumber(ctx context.Context, in *WorkerGetBlockNumberReq, opts ...grpc.CallOption) (*WorkerGetBlockNumberResp, error)
	// Find the salt in [0, max_salts) whose CREATE2 smart-wallet address
	// (under the given factory) matches target. The worker runs the scan +
	// comparison locally so a wide range is a single round-trip. Used by the
	// gateway's wallet-ownership validation (factory-upgrade fallback).
	FindMatchingWalletSalt(ctx context.Context, in *WorkerFindMatchingWalletSaltReq, opts ...grpc.CallOption) (*WorkerFindMatchingWalletSaltResp, error)
	// Read a transaction receipt by hash. Wraps ethclient.TransactionReceipt.
	// found=false when the receipt isn't available yet (pending). Used by the
	// gateway's userop confirmation-waiting to backfill gas data.
	GetTransactionReceipt(ctx context.Context, in *WorkerGetTransactionReceiptReq, opts ...grpc.CallOption) (*WorkerGetTransactionReceiptResp, error)
}

type chainWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewChainWorkerClient(cc grpc.ClientConnInterface) ChainWorkerClient {
	return &chainWorkerClient{cc}
}

func (c *chainWorkerClient) WorkerHealthCheck(ctx context.Context, in *WorkerHealthCheckReq, opts ...grpc.CallOption) (*WorkerHealthCheckResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerHealthCheckResp)
	err := c.cc.Invoke(ctx, ChainWorker_WorkerHealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) ExecuteUserOp(ctx context.Context, in *ExecuteUserOpReq, opts ...grpc.CallOption) (*ExecuteUserOpResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteUserOpResp)
	err := c.cc.Invoke(ctx, ChainWorker_ExecuteUserOp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) GetNonce(ctx context.Context, in *WorkerGetNonceReq, opts ...grpc.CallOption) (*WorkerGetNonceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerGetNonceResp)
	err := c.cc.Invoke(ctx, ChainWorker_GetNonce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) GetSmartWalletAddress(ctx context.Context, in *WorkerGetSmartWalletAddressReq, opts ...grpc.CallOption) (*WorkerGetSmartWalletAddressResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerGetSmartWalletAddressResp)
	err := c.cc.Invoke(ctx, ChainWorker_GetSmartWalletAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) GetTokenMetadata(ctx context.Context, in *WorkerGetTokenMetadataReq, opts ...grpc.CallOption) (*WorkerGetTokenMetadataResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerGetTokenMetadataResp)
	err := c.cc.Invoke(ctx, ChainWorker_GetTokenMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) GetNonceByAddress(ctx context.Context, in *WorkerGetNonceByAddressReq, opts ...grpc.CallOption) (*WorkerGetNonceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerGetNonceResp)
	err := c.cc.Invoke(ctx, ChainWorker_GetNonceByAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) SuggestGasPrice(ctx context.Context, in *WorkerSuggestGasPriceReq, opts ...grpc.CallOption) (*WorkerSuggestGasPriceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerSuggestGasPriceResp)
	err := c.cc.Invoke(ctx, ChainWorker_SuggestGasPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) EstimateGas(ctx context.Context, in *WorkerEstimateGasReq, opts ...grpc.CallOption) (*WorkerEstimateGasResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerEstimateGasResp)
	err := c.cc.Invoke(ctx, ChainWorker_EstimateGas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) GetCode(ctx context.Context, in *WorkerGetCodeReq, opts ...grpc.CallOption) (*WorkerGetCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerGetCodeResp)
	err := c.cc.Invoke(ctx, ChainWorker_GetCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) GetBalance(ctx context.Context, in *WorkerGetBalanceReq, opts ...grpc.CallOption) (*WorkerGetBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerGetBalanceResp)
	err := c.cc.Invoke(ctx, ChainWorker_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) GetTokenBalance(ctx context.Context, in *WorkerGetTokenBalanceReq, opts ...grpc.CallOption) (*WorkerGetTokenBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerGetTokenBalanceResp)
	err := c.cc.Invoke(ctx, ChainWorker_GetTokenBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) CallContract(ctx context.Context, in *WorkerCallContractReq, opts ...grpc.CallOption) (*WorkerCallContractResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerCallContractResp)
	err := c.cc.Invoke(ctx, ChainWorker_CallContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) GetBlockHeader(ctx context.Context, in *WorkerGetBlockHeaderReq, opts ...grpc.CallOption) (*WorkerGetBlockHeaderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerGetBlockHeaderResp)
	err := c.cc.Invoke(ctx, ChainWorker_GetBlockHeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) GetBlockNumber(ctx context.Context, in *WorkerGetBlockNumberReq, opts ...grpc.CallOption) (*WorkerGetBlockNumberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerGetBlockNumberResp)
	err := c.cc.Invoke(ctx, ChainWorker_GetBlockNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) FindMatchingWalletSalt(ctx context.Context, in *WorkerFindMatchingWalletSaltReq, opts ...grpc.CallOption) (*WorkerFindMatchingWalletSaltResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerFindMatchingWalletSaltResp)
	err := c.cc.Invoke(ctx, ChainWorker_FindMatchingWalletSalt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainWorkerClient) GetTransactionReceipt(ctx context.Context, in *WorkerGetTransactionReceiptReq, opts ...grpc.CallOption) (*WorkerGetTransactionReceiptResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerGetTransactionReceiptResp)
	err := c.cc.Invoke(ctx, ChainWorker_GetTransactionReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainWorkerServer is the server API for ChainWorker service.
// All implementations must embed UnimplementedChainWorkerServer
// for forward compatibility.
//
// ChainWorker is the internal gRPC service running on each chain worker.
// The gateway connects to workers by chain_id using addresses from config.
// Workers handle chain-specific operations: UserOp execution, nonce queries,
// smart wallet derivation, token enrichment, and gas estimation.
type ChainWorkerServer interface {
	// Health check - gateway verifies worker connectivity and chain status
	WorkerHealthCheck(context.Context, *WorkerHealthCheckReq) (*WorkerHealthCheckResp, error)
	// Execute a UserOp on this chain via the bundler
	ExecuteUserOp(context.Context, *ExecuteUserOpReq) (*ExecuteUserOpResp, error)
	// Get the nonce for a smart wallet on this chain
	GetNonce(context.Context, *WorkerGetNonceReq) (*WorkerGetNonceResp, error)
	// Get the smart wallet address for an owner on this chain
	GetSmartWalletAddress(context.Context, *WorkerGetSmartWalletAddressReq) (*WorkerGetSmartWalletAddressResp, error)
	// Get token metadata (enrichment) for a contract address on this chain
	GetTokenMetadata(context.Context, *WorkerGetTokenMetadataReq) (*WorkerGetTokenMetadataResp, error)
	// Get the nonce for an arbitrary smart wallet address on this chain.
	// Differs from GetNonce in that the caller already knows the wallet
	// address (looked up from gateway storage) and doesn't want to re-derive
	// it from (owner, salt). Used by REST handlers that read the nonce
	// directly off the EntryPoint contract.
	GetNonceByAddress(context.Context, *WorkerGetNonceByAddressReq) (*WorkerGetNonceResp, error)
	// Suggest a gas price for this chain. Wraps ethclient.SuggestGasPrice.
	// Used by the fee estimator to price UserOps.
	SuggestGasPrice(context.Context, *WorkerSuggestGasPriceReq) (*WorkerSuggestGasPriceResp, error)
	// Estimate gas for a contract call on this chain. Wraps
	// ethclient.EstimateGas with the same CallMsg shape ethclient takes.
	// Used by the fee estimator to gas-budget UserOp executions.
	EstimateGas(context.Context, *WorkerEstimateGasReq) (*WorkerEstimateGasResp, error)
	// Read the bytecode at a contract address. Wraps ethclient.CodeAt.
	// Used by the fee estimator to detect whether the runner contract is
	// deployed before issuing UserOps against it.
	GetCode(context.Context, *WorkerGetCodeReq) (*WorkerGetCodeResp, error)
	// Read the native-coin balance (wei) at an address. Wraps
	// ethclient.BalanceAt(latest). Used by the gateway's withdraw preflight
	// to validate / size native-token withdrawals.
	GetBalance(context.Context, *WorkerGetBalanceReq) (*WorkerGetBalanceResp, error)
	// Read an ERC-20 token balance for an owner. Wraps erc20.BalanceOf.
	// Used by the gateway's withdraw preflight to validate / size ERC-20
	// withdrawals.
	GetTokenBalance(context.Context, *WorkerGetTokenBalanceReq) (*WorkerGetTokenBalanceResp, error)
	// Execute a read-only contract call (eth_call) on this chain. Wraps
	// ethclient.CallContract. Used by the contractRead node so the gateway
	// issues no direct eth_call against execution chains.
	CallContract(context.Context, *WorkerCallContractReq) (*WorkerCallContractResp, error)
	// Read a block header's number, hash, and timestamp. Wraps
	// ethclient.HeaderByNumber. Used to stamp simulation receipts and
	// enrich event timestamps without a gateway-side chain dial.
	GetBlockHeader(context.Context, *WorkerGetBlockHeaderReq) (*WorkerGetBlockHeaderResp, error)
	// Read the latest block number. Wraps ethclient.BlockNumber. Used by the
	// immediate-trigger path to stamp the current block for the operator.
	GetBlockNumber(context.Context, *WorkerGetBlockNumberReq) (*WorkerGetBlockNumberResp, error)
	// Find the salt in [0, max_salts) whose CREATE2 smart-wallet address
	// (under the given factory) matches target. The worker runs the scan +
	// comparison locally so a wide range is a single round-trip. Used by the
	// gateway's wallet-ownership validation (factory-upgrade fallback).
	FindMatchingWalletSalt(context.Context, *WorkerFindMatchingWalletSaltReq) (*WorkerFindMatchingWalletSaltResp, error)
	// Read a transaction receipt by hash. Wraps ethclient.TransactionReceipt.
	// found=false when the receipt isn't available yet (pending). Used by the
	// gateway's userop confirmation-waiting to backfill gas data.
	GetTransactionReceipt(context.Context, *WorkerGetTransactionReceiptReq) (*WorkerGetTransactionReceiptResp, error)
	mustEmbedUnimplementedChainWorkerServer()
}

// UnimplementedChainWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChainWorkerServer struct{}

func (UnimplementedChainWorkerServer) WorkerHealthCheck(context.Context, *WorkerHealthCheckReq) (*WorkerHealthCheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkerHealthCheck not implemented")
}
func (UnimplementedChainWorkerServer) ExecuteUserOp(context.Context, *ExecuteUserOpReq) (*ExecuteUserOpResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteUserOp not implemented")
}
func (UnimplementedChainWorkerServer) GetNonce(context.Context, *WorkerGetNonceReq) (*WorkerGetNonceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNonce not implemented")
}
func (UnimplementedChainWorkerServer) GetSmartWalletAddress(context.Context, *WorkerGetSmartWalletAddressReq) (*WorkerGetSmartWalletAddressResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSmartWalletAddress not implemented")
}
func (UnimplementedChainWorkerServer) GetTokenMetadata(context.Context, *WorkerGetTokenMetadataReq) (*WorkerGetTokenMetadataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenMetadata not implemented")
}
func (UnimplementedChainWorkerServer) GetNonceByAddress(context.Context, *WorkerGetNonceByAddressReq) (*WorkerGetNonceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNonceByAddress not implemented")
}
func (UnimplementedChainWorkerServer) SuggestGasPrice(context.Context, *WorkerSuggestGasPriceReq) (*WorkerSuggestGasPriceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestGasPrice not implemented")
}
func (UnimplementedChainWorkerServer) EstimateGas(context.Context, *WorkerEstimateGasReq) (*WorkerEstimateGasResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateGas not implemented")
}
func (UnimplementedChainWorkerServer) GetCode(context.Context, *WorkerGetCodeReq) (*WorkerGetCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCode not implemented")
}
func (UnimplementedChainWorkerServer) GetBalance(context.Context, *WorkerGetBalanceReq) (*WorkerGetBalanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedChainWorkerServer) GetTokenBalance(context.Context, *WorkerGetTokenBalanceReq) (*WorkerGetTokenBalanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenBalance not implemented")
}
func (UnimplementedChainWorkerServer) CallContract(context.Context, *WorkerCallContractReq) (*WorkerCallContractResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallContract not implemented")
}
func (UnimplementedChainWorkerServer) GetBlockHeader(context.Context, *WorkerGetBlockHeaderReq) (*WorkerGetBlockHeaderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockHeader not implemented")
}
func (UnimplementedChainWorkerServer) GetBlockNumber(context.Context, *WorkerGetBlockNumberReq) (*WorkerGetBlockNumberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockNumber not implemented")
}
func (UnimplementedChainWorkerServer) FindMatchingWalletSalt(context.Context, *WorkerFindMatchingWalletSaltReq) (*WorkerFindMatchingWalletSaltResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMatchingWalletSalt not implemented")
}
func (UnimplementedChainWorkerServer) GetTransactionReceipt(context.Context, *WorkerGetTransactionReceiptReq) (*WorkerGetTransactionReceiptResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionReceipt not implemented")
}
func (UnimplementedChainWorkerServer) mustEmbedUnimplementedChainWorkerServer() {}
func (UnimplementedChainWorkerServer) testEmbeddedByValue()                     {}

// UnsafeChainWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainWorkerServer will
// result in compilation errors.
type UnsafeChainWorkerServer interface {
	mustEmbedUnimplementedChainWorkerServer()
}

func RegisterChainWorkerServer(s grpc.ServiceRegistrar, srv ChainWorkerServer) {
	// If the following call pancis, it indicates UnimplementedChainWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChainWorker_ServiceDesc, srv)
}

func _ChainWorker_WorkerHealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerHealthCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).WorkerHealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_WorkerHealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).WorkerHealthCheck(ctx, req.(*WorkerHealthCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_ExecuteUserOp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteUserOpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).ExecuteUserOp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_ExecuteUserOp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).ExecuteUserOp(ctx, req.(*ExecuteUserOpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_GetNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerGetNonceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).GetNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_GetNonce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).GetNonce(ctx, req.(*WorkerGetNonceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_GetSmartWalletAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerGetSmartWalletAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).GetSmartWalletAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_GetSmartWalletAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).GetSmartWalletAddress(ctx, req.(*WorkerGetSmartWalletAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_GetTokenMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerGetTokenMetadataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).GetTokenMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_GetTokenMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).GetTokenMetadata(ctx, req.(*WorkerGetTokenMetadataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_GetNonceByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerGetNonceByAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).GetNonceByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_GetNonceByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).GetNonceByAddress(ctx, req.(*WorkerGetNonceByAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_SuggestGasPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerSuggestGasPriceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).SuggestGasPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_SuggestGasPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).SuggestGasPrice(ctx, req.(*WorkerSuggestGasPriceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_EstimateGas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerEstimateGasReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).EstimateGas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_EstimateGas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).EstimateGas(ctx, req.(*WorkerEstimateGasReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_GetCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerGetCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).GetCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_GetCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).GetCode(ctx, req.(*WorkerGetCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerGetBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).GetBalance(ctx, req.(*WorkerGetBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_GetTokenBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerGetTokenBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).GetTokenBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_GetTokenBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).GetTokenBalance(ctx, req.(*WorkerGetTokenBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_CallContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerCallContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).CallContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_CallContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).CallContract(ctx, req.(*WorkerCallContractReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_GetBlockHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerGetBlockHeaderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).GetBlockHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_GetBlockHeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).GetBlockHeader(ctx, req.(*WorkerGetBlockHeaderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_GetBlockNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerGetBlockNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).GetBlockNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_GetBlockNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).GetBlockNumber(ctx, req.(*WorkerGetBlockNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_FindMatchingWalletSalt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerFindMatchingWalletSaltReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).FindMatchingWalletSalt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_FindMatchingWalletSalt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).FindMatchingWalletSalt(ctx, req.(*WorkerFindMatchingWalletSaltReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainWorker_GetTransactionReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerGetTransactionReceiptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainWorkerServer).GetTransactionReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainWorker_GetTransactionReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainWorkerServer).GetTransactionReceipt(ctx, req.(*WorkerGetTransactionReceiptReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ChainWorker_ServiceDesc is the grpc.ServiceDesc for ChainWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aggregator.ChainWorker",
	HandlerType: (*ChainWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WorkerHealthCheck",
			Handler:    _ChainWorker_WorkerHealthCheck_Handler,
		},
		{
			MethodName: "ExecuteUserOp",
			Handler:    _ChainWorker_ExecuteUserOp_Handler,
		},
		{
			MethodName: "GetNonce",
			Handler:    _ChainWorker_GetNonce_Handler,
		},
		{
			MethodName: "GetSmartWalletAddress",
			Handler:    _ChainWorker_GetSmartWalletAddress_Handler,
		},
		{
			MethodName: "GetTokenMetadata",
			Handler:    _ChainWorker_GetTokenMetadata_Handler,
		},
		{
			MethodName: "GetNonceByAddress",
			Handler:    _ChainWorker_GetNonceByAddress_Handler,
		},
		{
			MethodName: "SuggestGasPrice",
			Handler:    _ChainWorker_SuggestGasPrice_Handler,
		},
		{
			MethodName: "EstimateGas",
			Handler:    _ChainWorker_EstimateGas_Handler,
		},
		{
			MethodName: "GetCode",
			Handler:    _ChainWorker_GetCode_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _ChainWorker_GetBalance_Handler,
		},
		{
			MethodName: "GetTokenBalance",
			Handler:    _ChainWorker_GetTokenBalance_Handler,
		},
		{
			MethodName: "CallContract",
			Handler:    _ChainWorker_CallContract_Handler,
		},
		{
			MethodName: "GetBlockHeader",
			Handler:    _ChainWorker_GetBlockHeader_Handler,
		},
		{
			MethodName: "GetBlockNumber",
			Handler:    _ChainWorker_GetBlockNumber_Handler,
		},
		{
			MethodName: "FindMatchingWalletSalt",
			Handler:    _ChainWorker_FindMatchingWalletSalt_Handler,
		},
		{
			MethodName: "GetTransactionReceipt",
			Handler:    _ChainWorker_GetTransactionReceipt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker.proto",
}
