# this sets the logger level (true = info, false = debug)
production: false

# Replace with your operator
operator_address: 0x997E5D40a32c44a3D93E59fC55C4Fd20b7d2d49D

avs_registry_coordinator_address: 0x90c6d6f2A78d5Ce22AB8631Ddb142C03AC87De7a
operator_state_retriever_address: 0xb7bb920538e038DFFEfcB55caBf713652ED2031F

# Replace with your holesky RPC
eth_rpc_url: <holesky-eth-rpc-url>
eth_ws_url: <holesky-eth-wss-url>

ecdsa_private_key_store_path: <path-to-your-operator-ecdsa.key.json>
#ecdsa_private_key_store_path: alias-ecdsa.key.json

# If you running this using eigenlayer CLI and the provided AVS packaging structure,
# this should be /operator_keys/bls_key.json as the host path will be asked while running
#
# We are using bn254 curve for bls keys
#
# If you are running locally using go run main.go, this should be full path to your local bls key file
bls_private_key_store_path: <path-to-your-operator-bls.key.json>

aggregator_server_ip_port_address: "127.0.0.1:2206"

# avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
eigen_metrics_ip_port_address: localhost:9090
enable_metrics: true
node_api_ip_port_address: localhost:9010
enable_node_api: true

db_path: /tmp/ap-avs-operator

# Destination chain where the task run, relace with your actualy target chain
target_chain:
  eth_rpc_url: <sepolia-chain-rpc>
  eth_ws_url: <websocket-sepolia-chain-rpc>
