name: 'Setup Test Configuration'
description: 'Generate config/aggregator.yaml for CI unit tests'
inputs:
  chain-endpoint:
    description: 'Chain RPC endpoint domain (e.g., sepolia.infura.io/v3/KEY)'
    required: true
  bundler-rpc:
    description: 'Bundler RPC URL'
    required: true
  tenderly-account:
    description: 'Tenderly account name'
    required: true
  tenderly-project:
    description: 'Tenderly project name'
    required: true
  controller-private-key:
    description: 'Controller private key'
    required: true
  tenderly-access-key:
    description: 'Tenderly access key'
    required: true
  owner-eoa:
    description: 'Owner EOA address for test smart wallet derivation (controller signs UserOps)'
    required: true
  moralis-api-key:
    description: 'Moralis Web3 Data API key for token balance integration tests'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Generate and verify config/aggregator.yaml
      env:
        # Unified environment variables
        CHAIN_ENDPOINT: "${{ inputs.chain-endpoint }}"
        BUNDLER_RPC: "${{ inputs.bundler-rpc }}"

        # Tenderly HTTP API credentials
        TENDERLY_ACCOUNT: "${{ inputs.tenderly-account }}"
        TENDERLY_PROJECT: "${{ inputs.tenderly-project }}"

        # Secrets
        CONTROLLER_PRIVATE_KEY: "${{ inputs.controller-private-key }}"
        TENDERLY_ACCESS_KEY: "${{ inputs.tenderly-access-key }}"
        OWNER_EOA: "${{ inputs.owner-eoa }}"
        MORALIS_API_KEY: "${{ inputs.moralis-api-key }}"
      shell: bash
      run: ./.github/scripts/generate-test-config.sh
