name: 'Setup Test Configuration'
description: 'Generate config/aggregator.yaml for CI unit tests'
inputs:
  sepolia-rpc:
    description: 'Sepolia RPC URL'
    required: true
  sepolia-ws:
    description: 'Sepolia WebSocket URL'
    required: true
  sepolia-bundler-rpc:
    description: 'Sepolia Bundler RPC URL'
    required: true
  base-sepolia-rpc:
    description: 'Base Sepolia RPC URL'
    required: true
  base-sepolia-bundler-rpc:
    description: 'Base Sepolia Bundler RPC URL'
    required: true
  tenderly-account:
    description: 'Tenderly account name'
    required: true
  tenderly-project:
    description: 'Tenderly project name'
    required: true
  controller-private-key:
    description: 'Controller private key'
    required: true
  tenderly-access-key:
    description: 'Tenderly access key'
    required: true
  owner-eoa:
    description: 'Owner EOA address for test smart wallet derivation (controller signs UserOps)'
    required: true
  moralis-api-key:
    description: 'Moralis Web3 Data API key for token balance integration tests'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Generate and verify config/aggregator.yaml
      env:
        # Consolidated CI variables
        SEPOLIA_RPC: "${{ inputs.sepolia-rpc }}"
        SEPOLIA_WS: "${{ inputs.sepolia-ws }}"
        SEPOLIA_BUNDLER_RPC: "${{ inputs.sepolia-bundler-rpc }}"
        BASE_SEPOLIA_RPC: "${{ inputs.base-sepolia-rpc }}"
        BASE_SEPOLIA_BUNDLER_RPC: "${{ inputs.base-sepolia-bundler-rpc }}"

        # Tenderly HTTP API credentials
        TENDERLY_ACCOUNT: "${{ inputs.tenderly-account }}"
        TENDERLY_PROJECT: "${{ inputs.tenderly-project }}"

        # Secrets
        CONTROLLER_PRIVATE_KEY: "${{ inputs.controller-private-key }}"
        TENDERLY_ACCESS_KEY: "${{ inputs.tenderly-access-key }}"
        OWNER_EOA: "${{ inputs.owner-eoa }}"
        MORALIS_API_KEY: "${{ inputs.moralis-api-key }}"
      shell: bash
      run: ./.github/scripts/generate-test-config.sh
