package aggregator

import (
	"context"
	"fmt"
	"time"

	"github.com/AvaProtocol/EigenLayer-AVS/core/auth"
	"github.com/AvaProtocol/EigenLayer-AVS/core/config"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/golang-jwt/jwt/v5"
)

type CreateApiKeyOption struct {
	Roles   []string
	Subject string
}

// Create an JWT admin key to manage user task
func CreateAdminKey(configPath string, opt CreateApiKeyOption) error {
	nodeConfig, err := config.NewConfig(configPath)
	if err != nil {
		return fmt.Errorf("failed to parse config file: %s\nMake sure it is exist and a valid yaml file %w.", configPath, err)
	}

	aggregator, err := NewAggregator(nodeConfig)
	if err != nil {
		return fmt.Errorf("cannot initialize aggregator from config: %w", err)
	}

	if opt.Subject == "" {
		return fmt.Errorf("error: subject cannot be empty")
	}

	if !common.IsHexAddress(opt.Subject) {
		return fmt.Errorf("error: subject must be a valid 0x-prefixed EOA address (got %q). The subject is used as the owner identity bound to this API key.", opt.Subject)
	}

	if len(opt.Roles) < 1 {
		return fmt.Errorf("error: at least one role is required")
	}

	roles := make([]auth.ApiRole, len(opt.Roles))
	for i, v := range opt.Roles {
		roles[i] = auth.ApiRole(v)
	}

	// The verifier (aggregator/auth.go::verifyAuth) requires the JWT to have an
	// `aud` claim containing the chain ID string. NewAggregator does not run
	// the lifecycle init that populates agg.chainID, so dial the RPC directly
	// and read it here. Without this claim, every key generated by
	// `create-api-key` is rejected with "API key is invalid".
	rpcClient, err := ethclient.Dial(nodeConfig.EthHttpRpcUrl)
	if err != nil {
		return fmt.Errorf("failed to dial eth rpc to determine chainId for audience claim: %w", err)
	}
	defer rpcClient.Close()
	chainID, err := rpcClient.ChainID(context.Background())
	if err != nil {
		return fmt.Errorf("failed to fetch chainId for audience claim: %w", err)
	}

	claims := &auth.APIClaim{
		RegisteredClaims: &jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(time.Hour * 24 * 365 * 10)),
			Issuer:    "AvaProtocol",
			Subject:   opt.Subject,
			Audience:  jwt.ClaimStrings{chainID.String()},
		},
		Roles: roles,
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	ss, err := token.SignedString(aggregator.config.JwtSecret)

	fmt.Println(ss)

	return err
}
