genabi:
	abigen --abi=../abis/entrypoint.abi --pkg=aa --type=EntryPoint --out=entrypoint.go
	abigen --abi=../abis/factory.abi --pkg=aa --type=SimpleFactory --out=simplefactory.go
	abigen --abi=../abis/account.abi --pkg=simpleaccount --type=SimpleAccount --out=simpleaccount/simpleaccount.go
	abigen --abi=../abis/paymaster.abi --pkg=paymaster --type=PayMaster --out=paymaster/paymaster.go
