name: Deploy to Ethereum

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  deploy-avs:
    uses: ./.github/workflows/deploy-avs.yml
    with:
      environment: Ethereum
      directory: ethereum
    secrets:
      AVS_SSH_KEY: ${{ secrets.AVS_SSH_KEY }}
      AVS_SERVER_HOST: ${{ secrets.AVS_SERVER_HOST }}
