name: Deploy to Base

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  deploy-aggregator:
    uses: ./.github/workflows/deploy-avs.yml
    with:
      environment: Base
      directory: ${{ vars.DIRECTORY }} 