name: Deploy to Ethereum

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy-aggregator:
    uses: ./.github/workflows/deploy-aggregator.yml
    with:
      environment: Ethereum
      directory: ${{ vars.DIRECTORY }} 