name: Deploy to Base Sepolia

on:
  workflow_run:
    workflows: ["Publish dev build docker image to dockerhub"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-aggregator:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'Push' }}
    uses: ./.github/workflows/deploy-avs.yml
    with:
      environment: "Base Sepolia"
      directory: ${{ vars.DIRECTORY }} 