name: Deploy to Base Sepolia

on:
  workflow_run:
    workflows: ["Publish dev build docker image to dockerhub"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-avs:
    #if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'Push' }}
    uses: ./.github/workflows/deploy-avs.yml
    environment:
      name: "Base Sepolia"
    with:
      environment: "Base Sepolia"
      directory: ${{ vars.DIRECTORY }}
    secrets:
      AVS_SSH_KEY: ${{ secrets.AVS_SSH_KEY }}
      AVS_SERVER_HOST: ${{ secrets.AVS_SERVER_HOST }}