name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    environment: Test
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - aggregator
          - core/taskengine
          - core/taskengine/trigger
          - core/taskengine/macros
          - pkg/timekeeper
          - pkg/graphql
          - pkg/byte4
          - pkg/erc4337/preset
          - core/backup

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Go test
        env:
          RPC_URL: "${{ secrets.RPC_URL }}"
          BUNDLER_RPC: "${{ secrets.BUNDLER_RPC }}"
          FACTORY_ADDRESS: "${{ vars.FACTORY_ADDRESS }}"
          BASE_SEPOLIA_RPC_URL: "${{ secrets.BASE_SEPOLIA_RPC_URL }}"
          BASE_SEPOLIA_BUNDLER_RPC: "${{ secrets.BASE_SEPOLIA_BUNDLER_RPC }}"
          CONTROLLER_PRIVATE_KEY: "${{ secrets.CONTROLLER_PRIVATE_KEY }}"

        run: |
          cd ./${{ matrix.test }}
          go test . -v
