name: Build and Publish Docker from Dev Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        type: string

jobs:
  publish-dev-build:
    name: Publish dev build docker image to dockerhub
    runs-on: 'ubuntu-latest'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Configure QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Configure Docker Buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker image metadata and tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            avaprotocol/avs-dev
          tags: |
            type=raw,value=development
            type=raw,value={{sha}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push ap-avs-dev docker image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            RELEASE_TAG=${{ github.sha }}
            COMMIT_SHA=${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          context: .
          file: dockerfiles/operator.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
